Add files via upload
VolodymyrLiubashenko/AltexLabHomeWorks-Liubashenko-Vladimir pull request #5
Opened 2021-07-14 12:52 UTC by VolodymyrLiubashenko

2021-07-19 10:19 UTC, marynakorol requested changes

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/js/script.js
> +	boolean = false,
please change the  "boolean" name, you cannot use reserved words to avoid problems in future

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/js/script.js
> +	boolean = false,
if you need var as a flag here and it contains boolean it should be called from "is..." isVisible - e.g.

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/js/script.js
> +	fetch(`${baseUrl}/customers/${customerEditData.getId()}`, {
seems like the baseUrl may contain /customers appointment inside (if you always get just to this appointment)

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/js/script.js
> +		.then((data) => console.log(data));
GLOBAL:  remove all console.log()

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/js/script.js
> +	fetch(`${baseUrl}/customers`, {
try to add an additional function for fetch to optimize it (with params for url, headers and body)

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +	background: #ffffff;
please use vars if you use preprocessors

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +	z-index: 9999;
hope, you don't need such a big index :)

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +.custom-checkbox + .check {
use ampersand and nesting rule here:
& +.check {...} inside the .custom-checkbox

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +.custom-checkbox + .check::before {
same as 90 line

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +	width: 20px;
found 11 duplicates for 20px , so you can use var for it

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/style.scss
> +		width: 100%;
so big indent reformat your code please

2021-07-19 10:19 UTC, marynakorol commented on 4th-Project/source/variables.scss
> +$fontColorFirst: #000000;
do not use numbers for color variables it is not meaningful and it will be hard to figure out what var to use better to use primary for color that is mostly used on the project

2021-07-19 11:24 UTC, VolodymyrLiubashenko commented on 4th-Project/index.html
> +            <button  class="save-customer button " id="update-customer" disabled>Save changes</button>
deleted

2021-07-19 11:25 UTC, VolodymyrLiubashenko commented on 4th-Project/index.html
> +                            <button class="del-button del-all" id="del-all"></button>
I rename class into delete-button delete-all the same with id

2021-07-19 11:27 UTC, VolodymyrLiubashenko commented on 4th-Project/js/script.js
> +		.then((data) => console.log(data));
All console.log were deleted

2021-07-19 11:29 UTC, VolodymyrLiubashenko commented on 4th-Project/js/script.js
> +	fetch(`${baseUrl}/customers`, {
i dont understand this comment((((

2021-07-19 11:30 UTC, VolodymyrLiubashenko commented on 4th-Project/source/style.scss
> +	z-index: 9999;
me too

2021-07-19 11:34 UTC, VolodymyrLiubashenko commented on 4th-Project/source/style.scss
> +.custom-checkbox + .check {
.custom-checkbox {
	position: absolute;
	z-index: -1;
	opacity: 0;
	&+.check{
		display: inline-flex;
		align-items: center;
		user-select: none;
	}
	&+.check::before{
		content: "";
	width: 20px;
	height: 20px;
	border: 2px solid $bcSecond;
	border-radius: 5px;
	background-repeat: no-repeat;
	background-position: center center;
	background-size: 150% 150%;
	}
}
I made  like this

2021-07-19 11:37 UTC, VolodymyrLiubashenko commented on 4th-Project/source/variables.scss
> +$fontColorFirst: #000000;
How i should reName my variebles give me example plz

2021-07-19 11:38 UTC, VolodymyrLiubashenko commented on 4th-Project/source/style.scss
> +	background: #ffffff;
resolved

2021-07-19 11:40 UTC, VolodymyrLiubashenko commented on 4th-Project/source/style.scss
> +	width: 20px;
but it used for different properties..) how should i name this variable?)))

2021-07-19 11:42 UTC, VolodymyrLiubashenko commented on 4th-Project/js/script.js
> +	fetch(`${baseUrl}/customers/${customerEditData.getId()}`, {
but if i will have several array for ex not just customers, also guests, salers and so on...

2021-07-19 11:43 UTC, VolodymyrLiubashenko commented on 4th-Project/js/script.js
> +	boolean = false,
Marry i think you check  wrong version of my project(((

2021-07-19 11:44 UTC, VolodymyrLiubashenko commented on 4th-Project/index.html
> +<html>
dont understand.....(

2021-07-19 11:48 UTC, marynakorol commented on 4th-Project/index.html
> +<html>
<html lang="en">
...
</html>

2021-07-19 11:52 UTC, marynakorol commented on 4th-Project/js/script.js
> +	fetch(`${baseUrl}/customers/${customerEditData.getId()}`, {
yes, for the future, but I don't see anywhere in your project, if you wrote it thinking about future extending of your project, ok then may it remain

2021-07-19 11:54 UTC, marynakorol commented on 4th-Project/js/script.js
> +	boolean = false,
Marry? oh, thank you, but my heart is already taken;) Just call me Marina
about the version - I'll recheck

2021-07-22 18:52 UTC, marynakorol requested changes
pagination and filtration work good, just some reformat code required

2021-07-22 18:52 UTC, marynakorol commented on 4th-Project/source/style.scss
> +	width: 20px;
you can use it like indent-small and do not this var for font-size, e.g.

2021-07-22 18:52 UTC, marynakorol commented on 4th-Project/source/variables.scss
> +$fontColorFirst: #000000;
color-primary color-main or color-dark, color-secondary...

2021-07-22 18:52 UTC, marynakorol commented on 4th-Project/source/style.scss
> +.pagination {
please style inactive pages with grey, only active page number should have blue bg

2021-07-22 18:52 UTC, marynakorol commented on 4th-Project/source/variables.scss
> +$bcThird: #EFDBDB;
try to be consistent in your code, use all lowercase vars or all upper (#adb5bd; #EFDBDB;)

2021-07-22 18:52 UTC, marynakorol commented on 4th-Project/source/variables.scss
> +	&:before,&:after{
pseudoelements should be with double column (::)
and multiple selectors type in a column:
&:before,
&:after {

2021-07-23 09:30 UTC, VolodymyrLiubashenko commented on 4th-Project/source/variables.scss
> +	&:before,&:after{
fixed

2021-07-23 09:30 UTC, VolodymyrLiubashenko commented on 4th-Project/source/variables.scss
> +$bcThird: #EFDBDB;
fixed

2021-07-23 09:30 UTC, VolodymyrLiubashenko commented on 4th-Project/source/style.scss
> +.pagination {
fixed

2021-07-27 14:04 UTC, marynakorol approved these changes

2021-07-27 14:06 UTC, merged